### ISSUE TITLE
Singularities in NEI 

### ISSUE THREAD

**Issue by Cazadorsniper** [Wealthyturtle/Universal-Singularities#1]
Is it possible to remove disabled singularities from showing in NEI?

**Comment by Whimsyturtle** [comment]
It is possible to remove disabled singularities from showing up in NEI.
However, the disabled singularities may still be found under the Avaritia creative tab. Hope you're fine with it. :)
This update should take effect in Version 5.0 (to be released on Curse soon)

**Comment by WanionCane** [comment]
hey Mr.Cazador, here it is =P

[Universal Singularities - Version 5](https://minecraft.curseforge.com/projects/universal-singularities/files/2342673)

**Comment by Cazadorsniper** [comment]
Thank you :)

**Comment by WanionCane** [comment]
you are welcome :smile:
